version: "3.8"
name: educational-coding-platform

services:
  postgres:
    image: postgres:17.4
    command: postgres -c 'log_statement=all'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=main
    ports:
      - 5432:5432
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  judge0_server:
    image: judge0/judge0:latest
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    restart: always

  judge0_worker:
    image: judge0/judge0:latest
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    restart: always

  judge0_db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - judge0_data:/var/lib/postgresql/data/
    restart: always

  judge0_redis:
    image: redis:7.2.4
    command: ["bash", "-c", 'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"']
    env_file: judge0.conf
    restart: always

volumes:
  postgres_data:
  judge0_data:
